plugin:
  name: custom-data-type-finto
  version: 1.0
  url: https://github.com/programmfabrik/easydb-custom-data-type-finto
  displayname:
    de-DE: FINTO-Verknüpfung
    en-US: FINTO-Referencing
    fi-FI: FINTO-Pikakuvake
    sv-SE: FINTO-Genväg
  info:
    de-DE: Stellt Verknüpfungen zu dem finnischen Thesaurus- und Ontology-Service FINTO her
    en-US: Links to the Finnish thesaurus and ontology service FINTO
    fi-FI: Linkkejä suomalaiseen asiasanasto- ja ontologiapalveluun FINTO
    sv-SE: Länkar till den finska tesaurus- och ontologitjänsten FINTO
  l10n: l10n/customDataTypeFinto.csv
  webfrontend:
    url: customDataTypeFinto.js
    css: customDataTypeFinto.css

base_url_prefix: "webfrontend"

custom_types:
  finto:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
      conceptAncestors:
        type: text
      conceptSource:
        type: text
      facetTerm:
        type: text_l10n
    config:
      schema:
        - name: vocabulary_notation
          parameters:
            value:
              type: text
        - name: vocabulary_parent
          parameters:
            value:
              type: text
        - name: lang
          parameters:
            value:
              type: text
      mask:
        - name: editor_style
          parameters:
            value:
              type: select
              options: ["popover", "popover_treeview", "dropdown"]
        - name: allow_label_choice
          parameters:
            value:
              type: bool
    update:
      exec:
        service: "node"
        commands:
          - prog: "node"
            stdin:
              type: body
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/build/updater/customDataTypeFintoUpdater.js"
              - type: "value"
                value: "%info.json%"
      timeout: 60
      batch_size: 10
      expires_days: 1
      interval_base_config: update_interval_finto.days
base_config:
  - name: update_interval_finto
    group: update_custom_data_type
    parameters:
      days:
        type: int
        min: 0
        default: 0
        position: 0
      default_language:
        type: text
        default: 'fi'
        position: 1
